"""Schemas module initialization."""
from app.schemas.document import (
    DocumentMetadata,
    DocumentChunk,
    DocumentUploadResponse,
    DocumentListResponse,
    DocumentDeleteResponse,
)
from app.schemas.query import (
    QueryRequest,
    RetrievedChunk,
    QueryResponse,
)
from app.schemas.xml import (
    JobStatus,
    ProcessingStage,
    EntityType,
    AnforderungTyp,
    GraphRAGStrategy,
    ProcessingOptionsRequest,
    XMLUploadRequest,
    JobResponse,
    JobListResponse,
    ProcessingResultResponse,
    PresetConfigResponse,
    PresetListResponse,
    GraphSettingsRequest,
    GraphSettingsResponse,
    GraphNodeResponse,
    GraphEdgeResponse,
    GraphExplorationResponse,
    GraphStatsResponse,
)

__all__ = [
    "DocumentMetadata",
    "DocumentChunk",
    "DocumentUploadResponse",
    "DocumentListResponse",
    "DocumentDeleteResponse",
    "QueryRequest",
    "RetrievedChunk",
    "QueryResponse",
    # XML/Graph schemas
    "JobStatus",
    "ProcessingStage",
    "EntityType",
    "AnforderungTyp",
    "GraphRAGStrategy",
    "ProcessingOptionsRequest",
    "XMLUploadRequest",
    "JobResponse",
    "JobListResponse",
    "ProcessingResultResponse",
    "PresetConfigResponse",
    "PresetListResponse",
    "GraphSettingsRequest",
    "GraphSettingsResponse",
    "GraphNodeResponse",
    "GraphEdgeResponse",
    "GraphExplorationResponse",
    "GraphStatsResponse",
]
